trigger:
- main  

pool: myagent  

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin" 
    flutter doctor
  displayName: 'Install Flutter SDK'

- script: |
    flutter pub get 
  displayName: 'Install dependencies'

- script: |
    flutter build apk --release  
  displayName: 'Build Flutter project'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'build/app/outputs/flutter-apk/app-release.apk'  # Đường dẫn đến file APK
    artifact: 'FlutterApp'  # Tên artifact (bạn có thể đổi tên tùy ý)
    publishLocation: 'pipeline'  # Lưu artifact trong pipeline

- script: |
    echo "Deploying Flutter app..."
  displayName: 'Deploy project'
