trigger:
  branches:
    include:
      - main


pool: myagent  

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin" 
    flutter doctor
  displayName: 'Install Flutter SDK'

- script: |
    flutter pub get 
  displayName: 'Install dependencies'

- script: |
    flutter build apk --release  
  displayName: 'Build Flutter project'

- task: PublishPipelineArtifact@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  
    artifact: 'FlutterApp'  
    publishLocation: 'pipeline'

- script: |
    echo "Deploying Flutter app..."
  displayName: 'Deploy project'
