trigger:
- main  

pool: myagent  

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin" 
    flutter doctor
  displayName: 'Install Flutter SDK'

- script: |
    flutter pub get 
  displayName: 'Install dependencies'

- script: |
    flutter build apk  
  displayName: 'Build Flutter project'

- script: |
    echo "Deploying Flutter app..."
  displayName: 'Deploy project'
