trigger:
- main  # Khi có thay đổi trên nhánh 'main', pipeline sẽ được kích hoạt

pool:
  vmImage: ubuntu-latest  # Sử dụng máy ảo Ubuntu mới nhất

steps:
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './'
# Bước cài đặt Flutter SDK
- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin"  # Thêm Flutter vào PATH
    flutter doctor
  displayName: 'Install Flutter SDK'
